workflows:
  vue-android:
    name: Vue Android
    max_build_duration: 30
    environment:
      node: latest
      vars:
        PACKAGE_NAME: "com.oxygetv.app"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
      
      - name: Build Web
        script: |
          npm run build
          ls -la dist
      
      - name: Verify Environment
        script: |
          echo "=== Checking environment variables ==="
          if [ -z "$CM_KEYSTORE_PASSWORD" ]; then
            echo "Error: CM_KEYSTORE_PASSWORD is not set"
            exit 1
          fi
          if [ -z "$CM_KEY_PASSWORD" ]; then
            echo "Error: CM_KEY_PASSWORD is not set"
            exit 1
          fi
          echo "Environment variables are set correctly"
      
      - name: Setup Android
        script: |
          rm -rf android
          npx cap init OxygeTV com.oxygetv.app --web-dir=dist
          npx cap add android
          npx cap sync
          echo "=== Android directory structure ==="
          ls -la android
          echo "=== App directory structure ==="
          ls -la android/app
      
      - name: Setup Gradle
        script: |
          # Создаем settings.gradle
          cat > android/settings.gradle << 'EOF'
          include ':app'
          include ':capacitor-android'
          include ':capacitor-cordova-android-plugins'
          
          project(':capacitor-android').projectDir = new File('./capacitor/android')
          project(':capacitor-cordova-android-plugins').projectDir = new File('./capacitor-cordova-android-plugins/')
          
          rootProject.name = "OxygeTV"
          EOF
          
          # Создаем root build.gradle
          cat > android/build.gradle << 'EOF'
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:7.4.2'
              }
          }
          
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          
          task clean(type: Delete) {
              delete rootProject.buildDir
          }
          EOF
      
      - name: Generate keystore
        script: |
          keytool -genkey -v \
            -keystore keystore.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias upload \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            -dname "CN=OxygeTV, OU=Mobile, O=OxygeTV, L=Unknown, ST=Unknown, C=US" \
            -noprompt
      
      - name: Update Gradle Config
        script: |
          if [ -f "android/app/build.gradle" ]; then
            cp android/app/build.gradle android/app/build.gradle.bak
            cp build.gradle.template android/app/build.gradle
            echo "=== New build.gradle contents ==="
            cat android/app/build.gradle
          else
            echo "Error: build.gradle not found"
            exit 1
          fi
      
      - name: Build Android
        script: |
          echo "=== Android project structure before build ==="
          ls -R android/
          
          cd android
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            
            echo "=== Gradle version ==="
            ./gradlew --version
            
            echo "=== Available tasks ==="
            ./gradlew tasks
            
            echo "=== Project evaluation ==="
            ./gradlew projects
            
            echo "=== Dependencies ==="
            ./gradlew :app:dependencies
            
            echo "=== Building release ==="
            ./gradlew assembleRelease --info --stacktrace
          else
            echo "Error: gradlew not found"
            echo "=== Current directory contents ==="
            ls -la
            exit 1
          fi
    
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rzl44610@bcooq.com