workflows:
  vue-android:
    name: Vue Android
    max_build_duration: 30
    environment:
      node: latest
      vars:
        PACKAGE_NAME: "com.oxygetv.app"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init OxygeTV com.oxygetv.app --web-dir=dist
      
      - name: Build Web
        script: |
          npm run build
          ls -la dist  # Проверяем, что папка dist создана
      
      - name: Setup Android
        script: |
          npx cap add android
          npx cap sync
          ls -la android  # Проверяем, что папка android создана
          ls -la android/gradlew  # Проверяем, что gradlew существует
      
      - name: Generate keystore
        script: |
          keytool -genkey -v \
            -keystore keystore.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias upload \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            -dname "CN=OxygeTV, OU=Mobile, O=OxygeTV, L=Unknown, ST=Unknown, C=US" \
            -noprompt
      
      - name: Update Gradle Config
        script: |
          if [ -f "android/app/build.gradle" ]; then
            echo "android.signingConfigs.release.storeFile=../keystore.jks" >> android/app/build.gradle
            echo "android.signingConfigs.release.storePassword=$CM_KEYSTORE_PASSWORD" >> android/app/build.gradle
            echo "android.signingConfigs.release.keyAlias=upload" >> android/app/build.gradle
            echo "android.signingConfigs.release.keyPassword=$CM_KEY_PASSWORD" >> android/app/build.gradle
          else
            echo "Error: build.gradle not found"
            exit 1
          fi
      
      - name: Build Android
        script: |
          cd android
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleRelease
          else
            echo "Error: gradlew not found"
            exit 1
          fi
    
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rzl44610@bcooq.com